In [81]:
# import nesscessary library
import tensorflow as tf
from tensorflow import keras
import numpy as np

import sklearn
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score

In [82]:
# the environment uses CUDA 10.1 Tensorflow 2.2.0 sklearn 
print("GPU info:", tf.test.gpu_device_name())
print("Tensorflow verion is {}".format(tf.__version__))
print("Sklearn verion is {}".format(sklearn.__version__))

GPU info: /device:GPU:0
Tensorflow verion is 2.2.0
Sklearn verion is 0.24.1


In [83]:
# download and load dataset from tensorflow
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
# take a subset of the dataset
train_images, train_labels = train_images[0:2000], train_labels[0:2000]
test_images, test_labels = test_images[0:500], test_labels[0:500]

In [84]:
# reshape the dataset for aforementioned classifiers
# all of KNN, SGD, Descision Tree classifiers accept lower than 2-dim dataset
# so we need to reduce dimmension to 2
# first dim means number of the images
# second dim means true image data
train_images = train_images.reshape(2000, 784)
test_images = test_images.reshape(500, 784)

In [85]:
# KNN 
# initialize models
clf_knn = KNeighborsClassifier(n_neighbors = 3)
# fit models to training data
clf_knn.fit(train_images, train_labels)
# evaluate the test data(make predictions)
knn_predictions = clf_knn.predict(test_images)
knn_accuracy = accuracy_score(test_labels, knn_predictions)
recall = recall_score(test_labels, knn_predictions, average = 'macro')
con_mat = confusion_matrix(test_labels, knn_predictions)

print("KNN Accuracy:  %0.3f \t Recall: %0.3f " % (knn_accuracy, recall))
print("KNN confusion Matrix")
print(con_mat)

KNN Accuracy:  0.792 	 Recall: 0.801 
KNN confusion Matrix
[[46  1  2  1  0  0  5  0  0  0]
 [ 0 51  0  1  0  0  0  0  0  0]
 [ 3  0 43  1  9  0  9  0  0  0]
 [ 3  2  0 37  2  0  2  0  0  0]
 [ 1  1 10  4 31  0 10  0  0  0]
 [ 0  0  1  0  0 33  0  3  0  2]
 [ 6  0 12  2  2  0 25  0  0  0]
 [ 0  0  0  0  0  2  0 43  0  2]
 [ 1  0  2  0  0  0  0  0 41  0]
 [ 0  0  0  0  0  0  0  2  0 46]]


In [86]:
# SGD
# initialize models
clf_sgd = SGDClassifier(max_iter=250)
# fit models to training data
clf_sgd.fit(train_images, train_labels)
# evaluate the test data(make predictions)
sgd_predictions = clf_sgd.predict(test_images)
sgd_accuracy = accuracy_score(test_labels, sgd_predictions)
recall = recall_score(test_labels, sgd_predictions, average = 'macro')
con_mat = confusion_matrix(test_labels, sgd_predictions)

print("SGD Accuracy:  %0.3f \t Recall: %0.3f " % (sgd_accuracy, recall))
print("SGD confusion Matrix")
print(con_mat)

SGD Accuracy:  0.786 	 Recall: 0.794 
SGD confusion Matrix
[[52  0  0  1  0  0  2  0  0  0]
 [ 1 50  0  1  0  0  0  0  0  0]
 [ 2  0 43  2  8  0 10  0  0  0]
 [ 3  0  0 39  0  0  3  0  1  0]
 [ 1  0 16  4 29  0  6  1  0  0]
 [ 0  0  1  0  0 32  0  5  0  1]
 [12  0  6  4  0  0 24  0  1  0]
 [ 0  0  0  0  0  0  0 46  0  1]
 [ 0  0  0  1  0  0  3  0 40  0]
 [ 0  0  0  0  0  0  0 10  0 38]]


In [87]:
# Decision Tree
# initialize models
clf_dt = DecisionTreeClassifier()
# fit models to training data
clf_dt.fit(train_images, train_labels)
# evaluate the test data(make predictions)
dt_predictions = clf_dt.predict(test_images)
dt_accuracy = accuracy_score(test_labels, dt_predictions)
recall = recall_score(test_labels, dt_predictions, average = 'macro')
con_mat = confusion_matrix(test_labels, dt_predictions)

print("Decision Tree Accuracy:  %0.3f \t Recall: %0.3f " % (dt_accuracy, recall))
print("Decision Tree confusion Matrix")
print(con_mat)

Decision Tree Accuracy:  0.708 	 Recall: 0.723 
Decision Tree confusion Matrix
[[42  2  0  3  1  0  7  0  0  0]
 [ 1 46  0  4  0  0  1  0  0  0]
 [ 2  0 32  2 10  4 13  0  2  0]
 [ 1  1  0 36  1  0  6  0  1  0]
 [ 1  1 15  5 22  1 10  0  2  0]
 [ 0  0  0  0  0 33  0  3  1  2]
 [ 3  0  7  8  5  0 23  0  1  0]
 [ 0  0  0  0  0  0  0 45  0  2]
 [ 1  0  1  0  2  0  1  2 35  2]
 [ 0  0  0  0  0  2  0  6  0 40]]
